export const lostSessionsData = [
  {
    "id": 980,
    "trackId": 550,
    "name": "Покупатели и ритейлеры: аналитика, план действий по сокращению расходов и развитию продаж",
    "description": "Сессия коммерческих директоров / директоров по стратегии / владельцев бизнеса",
    "startTime": "11:00",
    "endTime": "12:30",
    "comments": null,
    "clients": null,
    "updatedAt": "2026-03-17T13:21:16.457Z",
    "managerId": null,
    "speakers": [
      {
        "id": 7990,
        "sessionId": 980,
        "speakerId": 107,
        "role": "moderator",
        "status": "confirmed",
        "statusDate": "2025-09-12T00:00:00.000Z",
        "sortOrder": 1,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": null,
        "positionSnapshot": "продюсер New Retail Forum",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "04653d6d-4791-40d7-a8d0-651dc32b15fb",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 107,
          "firstName": "Влад",
          "lastName": "Широбоков",
          "company": null,
          "position": "продюсер New Retail Forum",
          "email": "vladislav.shirobokov@gmail.com",
          "phone": null,
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7991,
        "sessionId": 980,
        "speakerId": 108,
        "role": "moderator",
        "status": "confirmed",
        "statusDate": "2025-09-12T00:00:00.000Z",
        "sortOrder": 2,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "UnyBrands",
        "positionSnapshot": "Founder",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "ac99684a-7304-41b3-b0af-a43c319a4bd1",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 108,
          "firstName": "Алла",
          "lastName": "Смородинова",
          "company": null,
          "position": "Founder UnyBrands",
          "email": null,
          "phone": "+7 925 852 1660",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7992,
        "sessionId": 980,
        "speakerId": 333,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 3,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "2025 году Fashion-рынок продолжает динамично меняться: новые поколения меняют правила игры в Fashion ритейле, растет доля онлайн-продаж, сила бренда и эмоции от шоппинга становятся ключевыми факторами в принятии решений о покупке. Мы в Gulliver, как и рынок, также меняемся и эти изменения обеспечивают нам устойчивый рост и развитие. Мы четко видим важность каждого канала для бизнеса, здоровую долю маркетплейсов в сплите, а также как оставаться любим брендом для нашего покупателя.",
        "presenceStatus": null,
        "companySnapshot": "Gulliver Group",
        "positionSnapshot": "Executive Director",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "c36526f7-980c-4296-bb6b-049633df0b5a",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 333,
          "firstName": "Оксана",
          "lastName": "Карпухина",
          "company": "Gulliver Group",
          "position": "Executive Director",
          "email": null,
          "phone": null,
          "telegram": null,
          "photoUrl": "https://storage.yandexcloud.net/speaker-photos.upgrade.st/oksana-karpuxina-717/default.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7993,
        "sessionId": 980,
        "speakerId": 109,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 4,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "Евгений Сахаров: Сегодня покупатель сантехники стал заметно требовательнее: цена по-прежнему имеет значение, но все чаще решающим становится скорость доставки и удобство получения заказа. Все большую роль играет и качество сервиса — от консультаций до гарантийной поддержки после покупки. В таких условиях в приоритете развитие процессов, которые позволяют предложить клиенту не только хороший ассортимент и выгодную цену, но и полный цикл: быстрый выбор, надежную доставку и сопровождение на всех этапах во всех каналах продаж.",
        "presenceStatus": null,
        "companySnapshot": "\"Сантехника-Онлайн\"",
        "positionSnapshot": "заместитель генерального директора",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "4087912d-9151-4ffb-b62c-ad5334cc2b17",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 109,
          "firstName": "Евгений",
          "lastName": "Сахаров",
          "company": null,
          "position": "заместитель генерального директора \"Сантехника-Онлайн\"",
          "email": null,
          "phone": "+7 926 466 8448",
          "telegram": null,
          "photoUrl": "/api/uploads/photos/speaker-109-023e47bd-0961-4ffb-9985-0052b714f41f.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7994,
        "sessionId": 980,
        "speakerId": 110,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 5,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Tom Tailor",
        "positionSnapshot": "генеральный директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "ec8f3d98-9bd6-4571-9c93-d568927b0611",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 110,
          "firstName": "Сергей",
          "lastName": "Кондаков",
          "company": null,
          "position": "генеральный директор Tom Tailor",
          "email": null,
          "phone": null,
          "telegram": "@lozhkinalena",
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7995,
        "sessionId": 980,
        "speakerId": 334,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-10-21T00:00:00.000Z",
        "sortOrder": 6,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "divan.ru",
        "positionSnapshot": "коммерческий директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "d3d595a4-d75a-4aab-a47c-24e4cc5674f3",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 334,
          "firstName": "Евгений",
          "lastName": "Романов",
          "company": "divan.ru",
          "position": "коммерческий директор",
          "email": null,
          "phone": null,
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7996,
        "sessionId": 980,
        "speakerId": 532,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 7,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "INFOLine-Аналитика",
        "positionSnapshot": "генеральный директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "16ab6650-92c3-46e9-9e29-4fd68cb6ef6c",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 532,
          "firstName": "Михаил",
          "lastName": "Бурмистров",
          "company": "INFOLine-Аналитика",
          "position": "генеральный директор",
          "email": "burmistrovmb@infoline.spb.ru",
          "phone": null,
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7997,
        "sessionId": 980,
        "speakerId": 112,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 8,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "ИЛЬ ДЕ БОТЭ",
        "positionSnapshot": "заместитель генерального директора по развитию бренда",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "b25aab6b-6414-4d66-a992-01a895026e71",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 112,
          "firstName": "Игорь",
          "lastName": "Тарасенко",
          "company": null,
          "position": "заместитель генерального директора по развитию бренда ИЛЬ ДЕ БОТЭ",
          "email": "itarasenko@iledebeaute.ru",
          "phone": "+7 903 792-22-85",
          "telegram": null,
          "photoUrl": "/api/uploads/photos/speaker-112-7e284346-1b5f-4a33-894e-07d0a1d21fe9.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7998,
        "sessionId": 980,
        "speakerId": 113,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": null,
        "sortOrder": 9,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "CORE.XP",
        "positionSnapshot": "директор подразделения представления интересов арендаторов",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "6c155887-0d16-4401-aa96-9da7f2f798fc",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 113,
          "firstName": "Евгений",
          "lastName": "Домашенко",
          "company": null,
          "position": "директор подразделения представления интересов арендаторов CORE.XP",
          "email": null,
          "phone": "89263108624",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 7999,
        "sessionId": 980,
        "speakerId": 114,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 10,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Диван. ру",
        "positionSnapshot": "основатель",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "b2f59fab-39a7-4062-ba64-96aa2545f8cf",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 114,
          "firstName": "Антон",
          "lastName": "Макаров",
          "company": null,
          "position": "основатель Диван. ру",
          "email": null,
          "phone": "+7 961 111-01-55",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8000,
        "sessionId": 980,
        "speakerId": 115,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-08-29T00:00:00.000Z",
        "sortOrder": 11,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "О'КЕЙ",
        "positionSnapshot": "коммерческий директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "dff398e1-be5e-4b3d-971a-1a48e499be26",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 115,
          "firstName": "Дмитрий",
          "lastName": "Пачин",
          "company": null,
          "position": "коммерческий директор О'КЕЙ",
          "email": null,
          "phone": "+7 921 757 6179",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8001,
        "sessionId": 980,
        "speakerId": 116,
        "role": "speaker",
        "status": "declined",
        "statusDate": null,
        "sortOrder": 12,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "ReStaff",
        "positionSnapshot": "руководитель направления внешних коммуникаций",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "966b04d8-36d7-4fe4-9786-52a8b7ab4acf",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 116,
          "firstName": "Артур",
          "lastName": "Муравьев",
          "company": null,
          "position": "руководитель направления внешних коммуникаций ReStaff",
          "email": null,
          "phone": "89817593168",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      }
    ],
    "questions": [
      {
        "id": 331,
        "sessionId": 980,
        "order": 1,
        "title": "#1",
        "body": "За что и почему готов платить покупатель в 2025 г.<br>- изменения в поведении покупателей, средне и долгосрочные тренды<br>- доходы населения и инфляция&nbsp;"
      },
      {
        "id": 332,
        "sessionId": 980,
        "order": 2,
        "title": "#2",
        "body": "Понимаем реальную расстановку сил на российском ритейл-рынке, адаптируем бизнес-планы.<br>- растущие бизнес-модели и ритейл-форматы, стоит ли все усилия фокусировать на маркетплейсах, т. к. они растут быстрее всех<br>- сравниваем привлекательность B2B и D2C E-Com бизнес-моделей (стоимость запуска / перспективы)<br>- технологии, трансформирующие ритейл-рынок: от AI и гиперсонализации к роботизации<br>- HR, варианты решения проблемы нехватки сотрудников любой квалификации"
      },
      {
        "id": 333,
        "sessionId": 980,
        "order": 3,
        "title": "#3",
        "body": "Оптимизация оффлайн-присутствия: от сокращения издержек к росту Brand Awareness<br>- актуальные тенденции рынка торговой недвижимости и их влияние на стратегии развития и оптимизации ритейла.<br>- сокращение расходов через правильное позиционирование и выбор локаций, что делает оффлайн-ритейл устойчивым в период спада продаж<br>- наиболее эффективные форматы ритейл-пространств. Гибридные форматы и эмоциональный ритейл: почему они набирают популярность?<br>- почему оффлайн все еще остается важным инструментом для построения Brand Awareness, а успешные E-Com проекты открывают шоу-румы"
      },
      {
        "id": 334,
        "sessionId": 980,
        "order": 4,
        "title": "#4",
        "body": "Приоритетные инструменты для поддержания продаж в период спада покупательской активности:<br>- рассрочки, программы лояльности<br>- омниканальность 2025 или почему у Золотого Яблока толпы покупателей во всех каналах продаж, а у Ленты самая высокая выручка с квадратного метра<br>- ритейл и услуги, покупатели хотят товары по лучшей цене или решение своих задач?"
      }
    ],
    "briefings": []
  },
  {
    "id": 981,
    "trackId": 550,
    "name": "Бизнес-модели и форматы, в которые инвестируют лидеры",
    "description": "Сессия владельцев и генеральных директоров",
    "startTime": "13:00",
    "endTime": "14:30",
    "comments": null,
    "clients": null,
    "updatedAt": "2026-03-17T13:21:16.747Z",
    "managerId": null,
    "speakers": [
      {
        "id": 8002,
        "sessionId": 981,
        "speakerId": 117,
        "role": "moderator",
        "status": "confirmed",
        "statusDate": "2025-09-12T00:00:00.000Z",
        "sortOrder": 1,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": null,
        "positionSnapshot": "основатель DigitalVoice, КРОССПРОМО, Ex Global Ecom Director ECCO",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "abbdc8d0-25cd-416d-9e6d-4724abf364d5",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 117,
          "firstName": "Филипп",
          "lastName": "Лабковский",
          "company": null,
          "position": "основатель DigitalVoice, КРОССПРОМО, Ex Global Ecom Director ECCO",
          "email": null,
          "phone": "+7 916 220-63-93",
          "telegram": "andy_al",
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8003,
        "sessionId": 981,
        "speakerId": 118,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-09-04T00:00:00.000Z",
        "sortOrder": 2,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Baon",
        "positionSnapshot": "генеральный директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "caa4c4d1-90e6-42a8-8673-ff8d5ab4df73",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 118,
          "firstName": "Илья",
          "lastName": "Ярошенко",
          "company": null,
          "position": "генеральный директор Baon",
          "email": null,
          "phone": "+7 926 409 5550",
          "telegram": null,
          "photoUrl": "/api/uploads/photos/speaker-118-61be0409-8883-49cd-94c0-d34ad01e2408.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8004,
        "sessionId": 981,
        "speakerId": 119,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 3,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "POIZON",
        "positionSnapshot": "региональный директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "4dd2e774-d1a3-418f-a284-84476d015fed",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 119,
          "firstName": "Дмитрий",
          "lastName": "Селихов",
          "company": null,
          "position": "региональный директор POIZON",
          "email": null,
          "phone": "+7 916 231-30-34",
          "telegram": null,
          "photoUrl": "/api/uploads/photos/speaker-119-6e834e64-d1e8-4ace-a25d-a254513d22cf.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8005,
        "sessionId": 981,
        "speakerId": 120,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-09-02T00:00:00.000Z",
        "sortOrder": 4,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Бетховен",
        "positionSnapshot": "СЕО, СОО",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "b9bd49ed-4914-4403-ad3b-481a34b67b47",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 120,
          "firstName": "Алексей",
          "lastName": "Пролыгин",
          "company": null,
          "position": "СЕО, СОО Бетховен",
          "email": null,
          "phone": "+7 916 221-62-71",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8006,
        "sessionId": 981,
        "speakerId": 342,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": null,
        "sortOrder": 5,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": "Повышение продаж с предиктивной аналитикой. Imredi insight • Быстрая реакция на изменения рынка • Все показатели сети в режиме онлайн в едином окне • Снижение расходов и потерь • Возможность быстро устранить проблемы по всей сети или отдельным магазинам/группам магазинов Не просто цифры, а подсказки для каждого сотрудника на основе аналитики, что нужно сделать, чтобы работать эффективнее.",
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Imredi",
        "positionSnapshot": "заместитель генерального директора по продажам и развитию бизнеса",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "59fab980-b8a1-4b04-bcf1-f72a400bf6e3",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 342,
          "firstName": "Максим",
          "lastName": "Семиренко",
          "company": "Imredi",
          "position": "заместитель генерального директора по продажам и развитию бизнеса",
          "email": null,
          "phone": null,
          "telegram": null,
          "photoUrl": "https://storage.yandexcloud.net/speaker-photos.upgrade.st/maksim-semirenko-728/default.webp",
          "isSponsor": false,
          "bio": "- предприниматель, опыт в бизнесе 7 лет, эксперт в автоматизации бизнес-процессов ритейле <br>- более 15 лет опыта в корпоративном управлении, эксперт в B2B продажах <br>- совладелец цифровой платформы Imredi для автоматизации ритейла с более чем 50 000 корпоративных пользователей, работающей с федеральными сетями Лента, Дикси, Бристоль, Винлаб и т.д.",
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8007,
        "sessionId": 981,
        "speakerId": 121,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-09-11T00:00:00.000Z",
        "sortOrder": 6,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Hobby World",
        "positionSnapshot": "сооснователь и генеральный директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "e55183e8-3690-4607-9fff-97fd613c31fe",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 121,
          "firstName": "Михаил",
          "lastName": "Акулов",
          "company": null,
          "position": "сооснователь и генеральный директор Hobby World",
          "email": null,
          "phone": null,
          "telegram": "@darksunrgb",
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8008,
        "sessionId": 981,
        "speakerId": 122,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-09-23T00:00:00.000Z",
        "sortOrder": 7,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "SWAIRS",
        "positionSnapshot": "CEO",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "c7e3578f-cd15-4d1f-914a-ff17017b7019",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 122,
          "firstName": "Андрей",
          "lastName": "Серегин",
          "company": null,
          "position": "CEO SWAIRS",
          "email": null,
          "phone": "+7 916 817 6238",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8009,
        "sessionId": 981,
        "speakerId": 123,
        "role": "speaker",
        "status": "declined",
        "statusDate": null,
        "sortOrder": 8,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Банк ВТБ (ПАО)",
        "positionSnapshot": "начальник управления \"Торгово-сервисные предприятия\", Блок СМБ",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "043fd45e-d243-4dab-8250-65a9aaa90dcf",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 123,
          "firstName": "Сергей",
          "lastName": "Панкин",
          "company": null,
          "position": "начальник управления \"Торгово-сервисные предприятия\", Блок СМБ Банк ВТБ (ПАО)",
          "email": "spankin@vtb.ru",
          "phone": "+7 916 212 31 13",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      }
    ],
    "questions": [
      {
        "id": 335,
        "sessionId": 981,
        "order": 1,
        "title": "#1",
        "body": "<b>Выбор ритейл-стратегий для 2025-2026 годов:</b><br>- сокращение: снижение издержек, закрытие убыточных бизнесов, оптимизация товарной матрицы<br>- диверсификации, выход на новые рынки и отрасли, не связанные с текущим бизнесом<br>- фокус на СТМ<br>- повышение качества сервиса<br>- концентрация на текущих продуктах и услугах<br>Дискуссия о важнейших трендах, определяющих развитие компаний в ритейл-сегментах.<br>Борьба за прибыльность, внимание и деньги покупателя, стратегии по запуску новых бизнес-моделей и форматов на фоне спада покупательской активности, консолидации рынка и растущего отрыва TOP30 игроков от конкурентов."
      },
      {
        "id": 336,
        "sessionId": 981,
        "order": 2,
        "title": "#2",
        "body": "<b>Привлечение инвестиций в ритейле:</b><br>- слияния и поглощения<br>- продажа бизнеса VS выход на IPO"
      },
      {
        "id": 337,
        "sessionId": 981,
        "order": 3,
        "title": "#3",
        "body": "<b>В какую инфраструктуру и бизнес-процессы необходимо продолжить инвестировать, от чего можно отказаться:</b><br><b>#3.1 Управление продажами через аналитику и алерты</b><br>презентация Imredi: Быстрая реакция на изменения рынка и повышение продаж с предиктивной аналитикой:<br>• все показатели сети в режиме онлайн в едином окне<br>• снижение расходов и потерь<br>• возможность быстро устранить проблемы по всей сети или отдельным магазинам/группам магазинов<br><b>#3.2 Безопасность и непрерывность бизнеса: покупатели и сотрудники, B2G:<br></b>презентация SWAIRS<br>• бизнес и безопасность вместе и врозь<br>• безопасность бизнес-процессов, как цель<br>• безопасность покупателей – залог планового среднего чека<br>• государство обеспечит порядок, безопасность обеспечит стратегия"
      }
    ],
    "briefings": []
  },
  {
    "id": 982,
    "trackId": 550,
    "name": "Маркетинговые стратегии",
    "description": "Сессия для директоров по маркетингу <br>Как выиграть в борьбе за внимание покупателей и в гонке маркетинговых бюджетов:",
    "startTime": "15:30",
    "endTime": "17:00",
    "comments": null,
    "clients": null,
    "updatedAt": "2026-03-17T13:21:16.808Z",
    "managerId": null,
    "speakers": [
      {
        "id": 8010,
        "sessionId": 982,
        "speakerId": 108,
        "role": "moderator",
        "status": "confirmed",
        "statusDate": "2025-09-12T00:00:00.000Z",
        "sortOrder": 1,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "UnyBrands",
        "positionSnapshot": "Founder",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "cf7bb7cd-ea4c-469d-ac8b-7f1282c0a617",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 108,
          "firstName": "Алла",
          "lastName": "Смородинова",
          "company": null,
          "position": "Founder UnyBrands",
          "email": null,
          "phone": "+7 925 852 1660",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8011,
        "sessionId": 982,
        "speakerId": 124,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 2,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "Ювелирный рынок находится в стадии активной трансформации: российские бренды уверенно занимают нишу сегментов Premium и High jewelry. Поэтому в настоящий момент мы фокусируемся на выводе в ассортимент сегмента «карат плюс» и персонализированных украшений, при этом сохраняя стабильным ядро ассортимента, понятное массовому покупателю.",
        "presenceStatus": null,
        "companySnapshot": "Адамас",
        "positionSnapshot": "CMO",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "43af4f0e-1303-4b82-a275-2a12ac3164c3",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 124,
          "firstName": "Ирина",
          "lastName": "Руденко",
          "company": null,
          "position": "CMO Адамас",
          "email": null,
          "phone": null,
          "telegram": "@me_ireen",
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8012,
        "sessionId": 982,
        "speakerId": 358,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 3,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "О'КЕЙ",
        "positionSnapshot": "Директор по коммерческим процессам и эффективности",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "70ce7411-5991-45c7-986c-6131a63fce77",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 358,
          "firstName": "Сюзанна",
          "lastName": "Риттер",
          "company": "О'КЕЙ",
          "position": "Директор по коммерческим процессам и эффективности",
          "email": null,
          "phone": null,
          "telegram": null,
          "photoUrl": "https://storage.yandexcloud.net/speaker-photos.upgrade.st/siuzanna-ritter-1823/default.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8013,
        "sessionId": 982,
        "speakerId": 125,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 4,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "Сосредоточиться на качестве продукции и потребностях клиента — фокус нашей стратегии на текущий и следующий год. Мы уже стали мебельными специалистами, но ближайший приоритет — удовлетворить запрос на широкий выбор товаров для обустройства жилых и общественных пространств. При этом мы заботливо лечим главную клиентскую боль — наш бренд не про «бабушкин дизайн», который заполонил рынок, а про модный внешний вид мебели. Опыт участия в зарубежных выставках и насмотренность играют нам на руку — мы следим за трендами и всегда остаёмся современными.",
        "presenceStatus": null,
        "companySnapshot": "divan.ru",
        "positionSnapshot": "директор по маркетингу",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "a5d0bc71-ac4e-470d-8c98-c715fd9a8f12",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 125,
          "firstName": "Марина",
          "lastName": "Филиппова",
          "company": null,
          "position": "директор по маркетингу divan.ru",
          "email": null,
          "phone": "+7 925 070 6617",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8014,
        "sessionId": 982,
        "speakerId": 126,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 5,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "В 2025 году мы видим смещение спроса на Китайские бренды электроники, всё больше новых брендов выходят на российский рынок, при этом конкуренция идет не только за счет цены, но также за счет потребительских свойств. При этом это не просто электроника ввезенная на российский рынок, многие китайские производители делают гаджеты совместимы с российским ПО, особенно что касается сфер умного дома. При этом мы видим более рациональное потребительское поведение, что приводит к снижению продаж, в особенности, мобильных гаджетов: смартфоны, планшеты, часы.",
        "presenceStatus": null,
        "companySnapshot": "Всёсмарт",
        "positionSnapshot": "CMO",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "c8c1ec33-a5e3-4827-afd8-c47913f4dcbe",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 126,
          "firstName": "Николай",
          "lastName": "Комаров",
          "company": null,
          "position": "CMO Всёсмарт",
          "email": null,
          "phone": "+79167343911",
          "telegram": null,
          "photoUrl": "/api/uploads/photos/speaker-126-37622e61-3d46-48f2-b66c-1343e238175b.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8015,
        "sessionId": 982,
        "speakerId": 127,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 6,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Hoff",
        "positionSnapshot": "директор по маркетингу",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "8d9c12cb-ac4b-4e5b-93c6-ab3334545103",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 127,
          "firstName": "Юлия",
          "lastName": "Мещерякова",
          "company": null,
          "position": "директор по маркетингу Hoff",
          "email": null,
          "phone": "+7 905 709 7214",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8016,
        "sessionId": 982,
        "speakerId": 366,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 7,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": "Ее выступление будет касаться human to human и эмоционального сервиса в оффлайн торговле.",
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "О'КЕЙ",
        "positionSnapshot": "CMO",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "b82557d2-dd36-4d70-a44d-d2b6c50cb51f",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 366,
          "firstName": "Елена",
          "lastName": "Шемагонова",
          "company": "О'КЕЙ",
          "position": "CMO",
          "email": null,
          "phone": null,
          "telegram": null,
          "photoUrl": "https://storage.yandexcloud.net/speaker-photos.upgrade.st/elena-semagonova-1556/default.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      }
    ],
    "questions": [
      {
        "id": 338,
        "sessionId": 982,
        "order": 1,
        "title": "#1",
        "body": "Ритейлеры и бренды<br>- баланс между долгосрочными инвестициями в бренд и краткосрочными задачами по поддержанию продаж<br>- планы по развитию собственных торговых марок<br>- в 2025 г. сосредотачиваемся на ценовом лидерстве и уменьшении издержек или дифференцируемся и находим свои ниши?<br>- примеры новых российских брендов, интересных ритейлерам и покупателям"
      },
      {
        "id": 339,
        "sessionId": 982,
        "order": 2,
        "title": "#2",
        "body": "В какие маркетинговые инструменты инвестирует лидеры рынка<br>- ритейл медиа<br>- автоматизация маркетинга и работа с данными<br>- CRM<br>- Performance"
      }
    ],
    "briefings": []
  },
  {
    "id": 983,
    "trackId": 550,
    "name": "Финансовая устойчивость: сокращаем риски, поддерживаем продажи",
    "description": "Сессия финансовых, коммерческих и E-Commerce директоров",
    "startTime": "17:30",
    "endTime": "18:30",
    "comments": null,
    "clients": null,
    "updatedAt": "2026-03-17T13:21:16.858Z",
    "managerId": null,
    "speakers": [
      {
        "id": 8017,
        "sessionId": 983,
        "speakerId": 108,
        "role": "moderator",
        "status": "confirmed",
        "statusDate": "2025-09-12T00:00:00.000Z",
        "sortOrder": 1,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "UnyBrands",
        "positionSnapshot": "Founder",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "1d7353fc-3f22-4459-b277-9637c5c2088f",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 108,
          "firstName": "Алла",
          "lastName": "Смородинова",
          "company": null,
          "position": "Founder UnyBrands",
          "email": null,
          "phone": "+7 925 852 1660",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8018,
        "sessionId": 983,
        "speakerId": 128,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-09-05T00:00:00.000Z",
        "sortOrder": 2,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "2025 год стал знаковым для российской электронной коммерции — впервые принят закон, регулирующий работу цифровых платформ. Сейчас все внимание отрасли направлено на то, как закон будет работать, когда вступит в силу. В зависимости от этого, можно будет говорить о дальнейшем развитии рынка\".",
        "presenceStatus": null,
        "companySnapshot": "Яндекс Маркет",
        "positionSnapshot": "финансовый директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "50f2a97f-727a-4be3-86f2-d102ab4c4287",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 128,
          "firstName": "Владислав",
          "lastName": "Склянов",
          "company": null,
          "position": "финансовый директор Яндекс Маркет",
          "email": null,
          "phone": null,
          "telegram": "@kseniavirchenko",
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8019,
        "sessionId": 983,
        "speakerId": 129,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-09-02T00:00:00.000Z",
        "sortOrder": 3,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Русклимат",
        "positionSnapshot": "начальник отдела корпоративного кредитования и страхования",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "1d830498-9433-4682-965b-432486d98a92",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 129,
          "firstName": "Анна",
          "lastName": "Бранашко",
          "company": null,
          "position": "начальник отдела корпоративного кредитования и страхования Русклимат",
          "email": null,
          "phone": "+7  985 60 64 53",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8020,
        "sessionId": 983,
        "speakerId": 372,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-09-24T00:00:00.000Z",
        "sortOrder": 4,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": null,
        "positionSnapshot": "руководитель программы Executive MBA Школы бизнеса МИРБИС, основатель Бизнес-Клуба Бизнес Одиссея",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "65b3d0e8-d319-40a1-8ef8-3f3b7f66a943",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 372,
          "firstName": "Николай",
          "lastName": "Мясников",
          "company": null,
          "position": "руководитель программы Executive MBA Школы бизнеса МИРБИС, основатель Бизнес-Клуба Бизнес Одиссея",
          "email": null,
          "phone": null,
          "telegram": null,
          "photoUrl": "https://storage.yandexcloud.net/speaker-photos.upgrade.st/nikolai-miasnikov-1671/default.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8021,
        "sessionId": 983,
        "speakerId": 130,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": null,
        "sortOrder": 5,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Точка Банк",
        "positionSnapshot": "эксперт в финансировании цепочек поставок.",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "6e271ac4-6a46-47d9-801e-dc70eb981bd5",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 130,
          "firstName": "Роман",
          "lastName": "Гайнуллин",
          "company": null,
          "position": "эксперт в финансировании цепочек поставок. Точка Банк",
          "email": null,
          "phone": "Эксперт по финансированию цепочек поставок",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8022,
        "sessionId": 983,
        "speakerId": 131,
        "role": "speaker",
        "status": "confirmed",
        "statusDate": "2025-09-08T00:00:00.000Z",
        "sortOrder": 6,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Vprok. ru (Перекресток | X5 Group)",
        "positionSnapshot": "Ex-коммерческий директор",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "803bd066-c880-470e-ac6d-25f2cc0014ac",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 131,
          "firstName": "Елена",
          "lastName": "Пудичева",
          "company": null,
          "position": "Ex-коммерческий директор Vprok. ru (Перекресток | X5 Group)",
          "email": null,
          "phone": null,
          "telegram": "@elena_pudicheva",
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8023,
        "sessionId": 983,
        "speakerId": 132,
        "role": "speaker",
        "status": "contact",
        "statusDate": "2025-08-22T00:00:00.000Z",
        "sortOrder": 7,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Лемана PRO",
        "positionSnapshot": "директор онлайн-бизнеса",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "2b1cd053-eeb0-4d6a-b668-9452332ed513",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 132,
          "firstName": "Максим",
          "lastName": "Трухин",
          "company": null,
          "position": "директор онлайн-бизнеса Лемана PRO",
          "email": null,
          "phone": "+79257728092",
          "telegram": null,
          "photoUrl": "/api/uploads/photos/speaker-132-2891d7d7-fb5a-4f1b-ab23-c78bd6266bfa.webp",
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8024,
        "sessionId": 983,
        "speakerId": 133,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-09-02T00:00:00.000Z",
        "sortOrder": 8,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "КАНТ",
        "positionSnapshot": "Генеральный директор, совладелец группы компаний",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "6bb8a207-6ad5-4e33-9ce5-9455af45c464",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 133,
          "firstName": "Максим",
          "lastName": "Виноградов",
          "company": null,
          "position": "Генеральный директор, совладелец группы компаний КАНТ",
          "email": "e.rasskazova@kant.ru",
          "phone": "+7 962 956 3001",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8025,
        "sessionId": 983,
        "speakerId": 134,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-09-02T00:00:00.000Z",
        "sortOrder": 9,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": "Значительный потенциал повышения прибыли кроется во внутренних процессах: их упрощение, стандартизация и автоматизация позволяют существенно повысить общую эффективность. В современных условиях, когда рынок демонстрирует замедление роста торговли в России и сталкивается с другими вызовами со стороны кадрового потенциала, покупательской способности и повышения ставок стоит пересмотреть свой фокус: не всегда ответы кроются в оптимизации внешних расходов. Именно подход работы с внутренними процессами помог METRO сократить административные издержки и увеличить прибыль, поделимся нашим кейсом на мероприятии",
        "presenceStatus": null,
        "companySnapshot": "METRO",
        "positionSnapshot": "директор финансового контроллинга",
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "c1666f36-fd12-4dac-9205-9d81ced6e44e",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 134,
          "firstName": "Светлана",
          "lastName": "Тимоненкова",
          "company": null,
          "position": "директор финансового контроллинга METRO",
          "email": null,
          "phone": "+79104252707",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      },
      {
        "id": 8026,
        "sessionId": 983,
        "speakerId": 135,
        "role": "speaker",
        "status": "declined",
        "statusDate": "2025-09-10T00:00:00.000Z",
        "sortOrder": 10,
        "needs_zoom": false,
        "hasPresentation": false,
        "managerComment": null,
        "programThesis": null,
        "newsletterQuote": null,
        "presenceStatus": null,
        "companySnapshot": "Хайв",
        "positionSnapshot": null,
        "presentationTitle": null,
        "presentationUrl": null,
        "memoHash": "577d8c00-c36b-4d94-80b6-bb1653da79d1",
        "notifiedEmail": false,
        "notifiedTg": false,
        "statusUserId": null,
        "exportToWebsite": true,
        "speaker": {
          "id": 135,
          "firstName": "Николай",
          "lastName": "Евченко",
          "company": null,
          "position": "Хайв",
          "email": null,
          "phone": "+79060929177",
          "telegram": null,
          "photoUrl": null,
          "isSponsor": false,
          "bio": null,
          "internalComment": null,
          "assistantContact": null,
          "assistantName": null,
          "hasAssistant": false
        }
      }
    ],
    "questions": [
      {
        "id": 340,
        "sessionId": 983,
        "order": 1,
        "title": "#1",
        "body": "Адаптация средне и долгосрочных финансовых стратегий к реалиям 2025 года"
      },
      {
        "id": 341,
        "sessionId": 983,
        "order": 2,
        "title": "#2",
        "body": "Финансовые риски, на которые необходимо обратить внимание в первую очередь"
      },
      {
        "id": 342,
        "sessionId": 983,
        "order": 3,
        "title": "#3",
        "body": "Привлечение внешнего финансирования в условиях высокой ставки: рабочие инструменты 2025 года<br>- кредитование<br>- факторинг<br>- выпуск облигаций<br>- IPO"
      },
      {
        "id": 343,
        "sessionId": 983,
        "order": 4,
        "title": "#4",
        "body": "Кейс банка Точка: \"Увеличение маржи через финансирование цепочек поставок\".<br>- как вы привыкли работать: через открытый факторинг с крупными поставщиками. Мелкие часто остаются не у дел. Да и вы зарабатываете разве что лишнюю операционку<br>- как можно: через динамическое дисконтирование. Можно с деньгами Точки, можно самостоятельно. Платите раньше, выигрываете несколько % маржи. А если на деньгах Точки, то даже платить раньше не надо<br>- кейсы из других, но близких отраслей: логистическая платформа Монополия и БелкаКар"
      },
      {
        "id": 344,
        "sessionId": 983,
        "order": 5,
        "title": "#5",
        "body": "Как пересчитать в деньги любую фичу"
      }
    ],
    "briefings": []
  }
];
