name: fix-db
on:
  workflow_dispatch:
jobs:
  fix-db:
    runs-on: ubuntu-24.04
    steps:
      - name: Fix DB
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker exec upgrade-crm-app-1 npx prisma migrate resolve --applied 20260317181300_sync_missing_needs_call
            docker exec upgrade-crm-app-1 npx prisma migrate deploy
